services:
  - type: web
    name: planning-poker
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:custom
    envVars:
      - key: NODE_ENV
        value: production
